version: '3'
services:
  mysql:
    image: mysql:8.0.2
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: sasa1234
      MYSQL_DATABASE: jpademo
      MYSQL_USER: luis
      MYSQL_PASSWORD: 123456
