version: '3'
services:
  mysql:
    image: mysql:8.4
    command: --mysql-native-password=ON
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: luis
      MYSQL_PASSWORD: 123456
